version: "3.9"
services:
  api:
    build: ./api
    environment:
      - DB_ADDRESS=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=CgT45n5rMoAXfye9QnX6qvpkxJ2TTE3i9VhwwDKxkDEBzsmzzs
      - DB_DATABASE=helpdesk
      - ADMIN_REGISTRATION_ALLOWED=False
      - JWT_SECRET=ywoXSoWt6ncj9o3Fct98inLt7EDVo4iWfNFitT6m8o
    ports:
      - "5000:5000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: CgT45n5rMoAXfye9QnX6qvpkxJ2TTE3i9VhwwDKxkDEBzsmzzs
      MYSQL_USER: helpdesk_user
      MYSQL_PASSWORD: dYBDzxPUZVD5Wx8h4M8eAn7RfBJiNtYBdu5A2C2gK4Dhum4c7F
    ports:
      - "3306:3306"
    volumes:
      - ./database-dump:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=CgT45n5rMoAXfye9QnX6qvpkxJ2TTE3i9VhwwDKxkDEBzsmzzs