name: Helpdesk deployment
run-name: ${{ github.actor }} deployment
on:
  push:
    branches:
      - main
      - unit-testing
jobs:
  code-style:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Frontend Eslint
        working-directory: ./frontend
        run: npm ci
        uses: eslint/github-action@v0

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "docker-compose.yaml"
          down-flags: "--volumes"